In [1]:
# !pip install pandas

In [2]:
import tweepy
import webbrowser
import time
import pandas as pd

In [3]:
consumer_key = "FVxmHgq4SpfM6A0kdN8JRr3Rd"
consumer_secret = "yshimrDc4edmltLhvjOmsaMAv8cf7S5VxgOuY2i17omeccbsLb"
callback_uri = 'oob'
auth = tweepy.OAuthHandler(consumer_key, consumer_secret, callback_uri)
redirect_url = auth.get_authorization_url()
webbrowser.open(redirect_url)
user_pint_input = input("What's the pin value? ")
auth.get_access_token(user_pint_input)

What's the pin value? 4485465

('173096823-DTCzZ8oLpEryUWBThUl214Fz9ot2sK2a2HoCglQU',
 '40dju3pGuQfmnqjEiuuEdNWrelvNoY2P4mR6E7RCF67uk')

In [4]:
api = tweepy.API(auth)

In [5]:
me = api.me()
me.screen_name

'videet_'

In [6]:
my_timeline = api.home_timeline()
# print(my_timline)

In [7]:
columns = set()
allowed_types = [str, int]
tweets_data = []
for status in my_timeline:
    print(status.author.screen_name)
    # print(type(vars(status)))
    status_dict = dict(vars(status))
    keys = status_dict.keys()
    single_tweet_data = {"user": status.user.screen_name, "author": status.author.screen_name}
    for k in keys:
        try:
            v_type = type(status_dict[k])
        except:
            v_type = None
        if v_type != None:
            if v_type in allowed_types:
                single_tweet_data[k] = status_dict[k]
                columns.add(k)
    tweets_data.append(single_tweet_data)

        
header_cols = list(columns)
header_cols.append("user")
header_cols.append('author')

9to5toys
9to5toys
9to5toys
9to5toys
nopecantdo
9to5toys
Stocktwits
bentcoder
13surroor
El_Cranko
jnadeau
13surroor
rxjshi
The_Sleigher
9to5toys
rxjshi
dankgifsonly
realpython
freeCodeCamp
dankgifsonly

In [8]:
header_cols

['source',
 'id_str',
 'lang',
 'in_reply_to_status_id_str',
 'in_reply_to_user_id',
 'in_reply_to_status_id',
 'text',
 'in_reply_to_screen_name',
 'quoted_status_id_str',
 'favorite_count',
 'retweet_count',
 'source_url',
 'quoted_status_id',
 'in_reply_to_user_id_str',
 'id',
 'user',
 'author']

In [9]:
tweets_data

[{'user': '9to5toys',
  'author': '9to5toys',
  'id': 1292903168981049344,
  'id_str': '1292903168981049344',
  'text': 'Amazon Big Summer Sale kitchenware deals from $4: Egg cooker, kettles, more https://t.co/YRvzhvTFCD by @justinkahnmusic',
  'source': '9to5Toys',
  'source_url': 'https://www.9to5toys.com',
  'retweet_count': 0,
  'favorite_count': 0,
  'lang': 'en'},
 {'user': '9to5toys',
  'author': '9to5toys',
  'id': 1292902622693916680,
  'id_str': '1292902622693916680',
  'text': 'WD’s budget-friendly 500GB NVMe SSD offers R/W speeds of up to 3.4GB/s at just $70 shipped https://t.co/6ff5R1TQdM https://t.co/l8onnD51k7',
  'source': 'TweetDeck',
  'source_url': 'https://about.twitter.com/products/tweetdeck',
  'retweet_count': 3,
  'favorite_count': 3,
  'lang': 'en'},
 {'user': '9to5toys',
  'author': '9to5toys',
  'id': 1292902436504510464,
  'id_str': '1292902436504510464',
  'text': 'Amazon Fashion x Vogue launches a designer storefront with funds for COVID-19 https://t.co/Ds6HDViaxG by @alismithstyle',
  'source': '9to5Toys',
  'source_url': 'https://www.9to5toys.com',
  'retweet_count': 0,
  'favorite_count': 0,
  'lang': 'en'},
 {'user': '9to5toys',
  'author': '9to5toys',
  'id': 1292902079707709440,
  'id_str': '1292902079707709440',
  'text': 'Head back to school with a new Apple Watch band from $7.50 in various styles https://t.co/iykLtQ5fIy by @trevorjd14',
  'source': '9to5Toys',
  'source_url': 'https://www.9to5toys.com',
  'retweet_count': 0,
  'favorite_count': 0,
  'lang': 'en'},
 {'user': 'nopecantdo',
  'author': 'nopecantdo',
  'id': 1292901690375417857,
  'id_str': '1292901690375417857',
  'text': 'And I still can’t afford to get my own place https://t.co/FPIielXnMj',
  'source': 'Twitter for iPhone',
  'source_url': 'http://twitter.com/download/iphone',
  'quoted_status_id': 1290270281789919232,
  'quoted_status_id_str': '1290270281789919232',
  'retweet_count': 0,
  'favorite_count': 0,
  'lang': 'en'},
 {'user': '9to5toys',
  'author': '9to5toys',
  'id': 1292901604027437058,
  'id_str': '1292901604027437058',
  'text': 'Save up to 25% on HP printers with AirPrint, Alexa, more starting at $100 https://t.co/3hN9v0VQD0 by @blairaltland',
  'source': '9to5Toys',
  'source_url': 'https://www.9to5toys.com',
  'retweet_count': 1,
  'favorite_count': 0,
  'lang': 'en'},
 {'user': 'Stocktwits',
  'author': 'Stocktwits',
  'id': 1292901424628551680,
  'id_str': '1292901424628551680',
  'text': 'RT @callieabost: Well well well...would ya look at the transport stocks.\n\nHeading for their ninth up day in a row, the longest winning stre…',
  'source': 'Twitter for iPhone',
  'source_url': 'http://twitter.com/download/iphone',
  'retweet_count': 4,
  'favorite_count': 0,
  'lang': 'en'},
 {'user': 'bentcoder',
  'author': 'bentcoder',
  'id': 1292901260417355776,
  'id_str': '1292901260417355776',
  'text': 'Mood... https://t.co/IQZhD3om0r',
  'source': 'Twitter for iPhone',
  'source_url': 'http://twitter.com/download/iphone',
  'retweet_count': 0,
  'favorite_count': 2,
  'lang': 'en'},
 {'user': '13surroor',
  'author': '13surroor',
  'id': 1292900987515088897,
  'id_str': '1292900987515088897',
  'text': 'RT @comradec0re: “capitalism breeds innovation!!!!” https://t.co/QmCdh47naO',
  'source': 'Twitter for Android',
  'source_url': 'http://twitter.com/download/android',
  'retweet_count': 3209,
  'favorite_count': 0,
  'lang': 'en'},
 {'user': 'El_Cranko',
  'author': 'El_Cranko',
  'id': 1292900852286382081,
  'id_str': '1292900852286382081',
  'text': 'ZNMD - Dil Aakhir Tu Kyun Rota Hai   https://t.co/FsI51jNrye',
  'source': 'Twitter for iPhone',
  'source_url': 'http://twitter.com/download/iphone',
  'retweet_count': 0,
  'favorite_count': 1,
  'lang': 'in'},
 {'user': 'jnadeau',
  'author': 'jnadeau',
  'id': 1292900372579627008,
  'id_str': '1292900372579627008',
  'text': 'RT @Struggle_Tweet: https://t.co/24r34eJkq7',
  'source': 'Twitter for iPhone',
  'source_url': 'http://twitter.com/download/iphone',
  'retweet_count': 2994,
  'favorite_count': 0,
  'lang': 'und'},
 {'user': '13surroor',
  'author': '13surroor',
  'id': 1292900195131424769,
  'id_str': '1292900195131424769',
  'text': 'RT @InnocentNudess: Sorry I am late i was masturbating',
  'source': 'Twitter for Android',
  'source_url': 'http://twitter.com/download/android',
  'retweet_count': 162,
  'favorite_count': 0,
  'lang': 'en'},
 {'user': 'rxjshi',
  'author': 'rxjshi',
  'id': 1292900050436227076,
  'id_str': '1292900050436227076',
  'text': 'no bulls were chasing him in the last scene to distract you from real content. https://t.co/yrd3UMQZgv',
  'source': 'Twitter Web App',
  'source_url': 'https://mobile.twitter.com',
  'in_reply_to_status_id': 1292899307369238528,
  'in_reply_to_status_id_str': '1292899307369238528',
  'in_reply_to_user_id': 883773132493864961,
  'in_reply_to_user_id_str': '883773132493864961',
  'in_reply_to_screen_name': 'rxjshi',
  'retweet_count': 0,
  'favorite_count': 3,
  'lang': 'en'},
 {'user': 'The_Sleigher',
  'author': 'The_Sleigher',
  'id': 1292899539720916997,
  'id_str': '1292899539720916997',
  'text': 'RT @Ahir_belivess: @mufaddal_vohra Is this true?? 😳 https://t.co/TVihc21F7H',
  'source': 'Twitter for Android',
  'source_url': 'http://twitter.com/download/android',
  'retweet_count': 21,
  'favorite_count': 0,
  'lang': 'en'},
 {'user': '9to5toys',
  'author': '9to5toys',
  'id': 1292899447148613635,
  'id_str': '1292899447148613635',
  'text': "ROCCAT's Vulcan 100 AIMO RGB keyboard returns to Amazon low at $110 https://t.co/HnmOrKGpJ6 by @pcamp96",
  'source': '9to5Toys',
  'source_url': 'https://www.9to5toys.com',
  'retweet_count': 0,
  'favorite_count': 1,
  'lang': 'en'},
 {'user': 'rxjshi',
  'author': 'rxjshi',
  'id': 1292899307369238528,
  'id_str': '1292899307369238528',
  'text': 'DCH is a whole film it shows the uncomfortable side as well. ZNMD values the happy path more. Little takeaways. In… https://t.co/QOuo7aMKqn',
  'source': 'Twitter Web App',
  'source_url': 'https://mobile.twitter.com',
  'quoted_status_id': 1292891196906332161,
  'quoted_status_id_str': '1292891196906332161',
  'retweet_count': 0,
  'favorite_count': 2,
  'lang': 'en'},
 {'user': 'dankgifsonly',
  'author': 'dankgifsonly',
  'id': 1292898976086159366,
  'id_str': '1292898976086159366',
  'text': "RT @aniket0608: Here's your 'culture' cokehead. https://t.co/dajV8wuAUq",
  'source': 'Twitter for Android',
  'source_url': 'http://twitter.com/download/android',
  'quoted_status_id': 1291309395293478912,
  'quoted_status_id_str': '1291309395293478912',
  'retweet_count': 5,
  'favorite_count': 0,
  'lang': 'en'},
 {'user': 'realpython',
  'author': 'realpython',
  'id': 1292898772251549698,
  'id_str': '1292898772251549698',
  'text': "RT @realpython: Pycoder's Weekly have recently introduced it's archive feature. Check out past issues here: https://t.co/Cjbw03KkU2 #python",
  'source': 'SocialBee.io v2',
  'source_url': 'https://socialbee.io/',
  'retweet_count': 19,
  'favorite_count': 0,
  'lang': 'en'},
 {'user': 'freeCodeCamp',
  'author': 'freeCodeCamp',
  'id': 1292898764219453441,
  'id_str': '1292898764219453441',
  'text': "So you want to start learning React, one of the most popular JavaScript libs out there, eh?\n\nWell, you've come to t… https://t.co/pPGo90t7G2",
  'source': 'Buffer',
  'source_url': 'https://buffer.com',
  'retweet_count': 11,
  'favorite_count': 41,
  'lang': 'en'},
 {'user': 'dankgifsonly',
  'author': 'dankgifsonly',
  'id': 1292898406457683969,
  'id_str': '1292898406457683969',
  'text': 'RT @BNONews: WATCH: Massive explosion rips through gas station in southwest Russia; at least 13 injured https://t.co/6oA2vdYf42',
  'source': 'Twitter for Android',
  'source_url': 'http://twitter.com/download/android',
  'retweet_count': 5613,
  'favorite_count': 0,
  'lang': 'en'}]

In [10]:
df = pd.DataFrame(tweets_data, columns=header_cols)
df.head()

,source,id_str,lang,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_status_id,text,in_reply_to_screen_name,quoted_status_id_str,favorite_count,retweet_count,source_url,quoted_status_id,in_reply_to_user_id_str,id,user,author
0,9to5Toys,1292903168981049344,en,NaN,NaN,NaN,Amazon Big Summer Sale kitchenware deals from ...,NaN,NaN,0,0,https://www.9to5toys.com,NaN,NaN,1292903168981049344,9to5toys,9to5toys
1,TweetDeck,1292902622693916680,en,NaN,NaN,NaN,WD’s budget-friendly 500GB NVMe SSD offers R/W...,NaN,NaN,3,3,https://about.twitter.com/products/tweetdeck,NaN,NaN,1292902622693916680,9to5toys,9to5toys
2,9to5Toys,1292902436504510464,en,NaN,NaN,NaN,Amazon Fashion x Vogue launches a designer sto...,NaN,NaN,0,0,https://www.9to5toys.com,NaN,NaN,1292902436504510464,9to5toys,9to5toys
3,9to5Toys,1292902079707709440,en,NaN,NaN,NaN,Head back to school with a new Apple Watch ban...,NaN,NaN,0,0,https://www.9to5toys.com,NaN,NaN,1292902079707709440,9to5toys,9to5toys
4,Twitter for iPhone,1292901690375417857,en,NaN,NaN,NaN,And I still can’t afford to get my own place h...,NaN,1290270281789919232,0,0,http://twitter.com/download/iphone,1.290270e+18,NaN,1292901690375417857,nopecantdo,nopecantdo

In [11]:
def extract_timeline_as_df(timeline_list):
    columns = set()
    allowed_types = [str, int]
    tweets_data = []
    for status in timeline_list:
        status_dict = dict(vars(status))
        keys = status_dict.keys()
        single_tweet_data = {"user": status.user.screen_name, "author": status.author.screen_name}
        for k in keys:
            try:
                v_type = type(status_dict[k])
            except:
                v_type = None
            if v_type != None:
                if v_type in allowed_types:
                    single_tweet_data[k] = status_dict[k]
                    columns.add(k)
        tweets_data.append(single_tweet_data)


    header_cols = list(columns)
    header_cols.append("user")
    header_cols.append('author')
    df = pd.DataFrame(tweets_data, columns=header_cols)
    return df

In [12]:
my_timeline = api.home_timeline()

In [13]:
df2 = extract_timeline_as_df(my_timeline)
df2.head()

,source,id_str,lang,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_status_id,text,in_reply_to_screen_name,quoted_status_id_str,favorite_count,retweet_count,source_url,quoted_status_id,in_reply_to_user_id_str,id,user,author
0,9to5Toys,1292903168981049344,en,NaN,NaN,NaN,Amazon Big Summer Sale kitchenware deals from ...,NaN,NaN,0,0,https://www.9to5toys.com,NaN,NaN,1292903168981049344,9to5toys,9to5toys
1,TweetDeck,1292902622693916680,en,NaN,NaN,NaN,WD’s budget-friendly 500GB NVMe SSD offers R/W...,NaN,NaN,3,3,https://about.twitter.com/products/tweetdeck,NaN,NaN,1292902622693916680,9to5toys,9to5toys
2,9to5Toys,1292902436504510464,en,NaN,NaN,NaN,Amazon Fashion x Vogue launches a designer sto...,NaN,NaN,0,0,https://www.9to5toys.com,NaN,NaN,1292902436504510464,9to5toys,9to5toys
3,9to5Toys,1292902079707709440,en,NaN,NaN,NaN,Head back to school with a new Apple Watch ban...,NaN,NaN,0,0,https://www.9to5toys.com,NaN,NaN,1292902079707709440,9to5toys,9to5toys
4,Twitter for iPhone,1292901690375417857,en,NaN,NaN,NaN,And I still can’t afford to get my own place h...,NaN,1290270281789919232,0,0,http://twitter.com/download/iphone,1.290270e+18,NaN,1292901690375417857,nopecantdo,nopecantdo

In [ ]:
user = api.get_user("code")
user_timeline = user.timeline()
df3 = extract_timeline_as_df(user_timeline)
df3.head()